import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sfProDisplayRegular = localFont({
  src: "../public/fonts/SFPRODISPLAYREGULAR.woff2",
  variable: "--font-sf-regular",
});

const sfProDisplayMedium = localFont({
  src: "../public/fonts/SFPRODISPLAYMEDIUM.woff2",
  variable: "--font-sf-medium",
});

const sfProDisplayLightItalic = localFont({
  src: "../public/fonts/SFPRODISPLAYLIGHTITALIC.woff2",
  variable: "--font-sf-light-italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfProDisplayRegular.variable} ${sfProDisplayMedium.variable} ${sfProDisplayLightItalic.variable} antialiased relative`}
      >
        {/* Вертикальные границы 1440px */}
        <div className="fixed inset-0 pointer-events-none z-50">
          <div className="max-w-[1440px] mx-auto h-full border-x-2 border-[#ECECEC]"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
